name: Build Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate news
        run: python scripts/news/news.py
      - name: Ingest sources
        run: python scripts/ingest/ingest.py
      - name: Lint sources
        run: python scripts/ingest/lint_sources.py
      - name: Build docs
        run: mkdocs build --strict
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
      - uses: actions/upload-artifact@v4
        with:
          name: sources
          path: docs/sources

  nightly-news:
    runs-on: ubuntu-latest
    schedule:
      - cron: '0 6 * * *'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate news
        run: python scripts/news/news.py
      - name: Build docs
        run: mkdocs build --strict
      - uses: actions/upload-artifact@v4
        with:
          name: site-nightly
          path: site